application: angular-gmail
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /angular-gmail\.js
  static_files: angular-gmail.js
  upload: angular-gmail\.js

- url: .*
  static_files: main.html
  upload: main\.html

